# Generated by Django 5.0.3 on 2024-03-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchwise', '0003_genre_alter_media_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='release_date',
        ),
        migrations.AddField(
            model_name='media',
            name='release_year',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
