# Generated by Django 5.0.3 on 2024-03-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchwise', '0004_remove_media_release_date_media_release_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MediaType',
            new_name='Type',
        ),
    ]
