# Generated by Django 4.2.11 on 2024-03-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchwise', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.IntegerField()),
                ('overview', models.TextField()),
                ('original_language', models.CharField(max_length=2)),
                ('status', models.CharField(choices=[('already_seen', 'Already Seen'), ('wishlist', 'Wishlist'), ('not_interested', 'Not Interested')], default='wishlist', max_length=14)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TV_Shows',
            fields=[
                ('TV_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('first_air_date', models.IntegerField()),
                ('overview', models.TextField()),
                ('original_language', models.CharField(max_length=2)),
                ('status', models.CharField(choices=[('already_seen', 'Already Seen'), ('wishlist', 'Wishlist'), ('not_interested', 'Not Interested')], default='wishlist', max_length=14)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
