# Generated by Django 5.0.3 on 2024-03-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchwise', '0007_movie_tv_shows'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TV_Shows',
            new_name='TVShow',
        ),
        migrations.RemoveField(
            model_name='media',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='media',
            name='media_type',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
