# Generated by Django 5.0.3 on 2024-04-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchwise', '0008_rename_tv_shows_tvshow_remove_media_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('watched', 'Watched'), ('wishlist', 'Wishlist'), ('not_interested', 'Not Interested')], default='wishlist', max_length=14),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='status',
            field=models.CharField(choices=[('watched', 'Watched'), ('wishlist', 'Wishlist'), ('not_interested', 'Not Interested')], default='wishlist', max_length=14),
        ),
    ]
