# Generated by Django 4.2.11 on 2024-04-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchwise', '0009_alter_movie_status_alter_tvshow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('watched', 'Watched'), ('watchlist', 'Watchlist'), ('not_interested', 'Not Interested')], default='watchlist', max_length=14),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='status',
            field=models.CharField(choices=[('watched', 'Watched'), ('watchlist', 'Watchlist'), ('not_interested', 'Not Interested')], default='watchlist', max_length=14),
        ),
    ]
