# Generated by Django 4.2.11 on 2024-04-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchwise', '0012_alter_movie_rating_alter_tvshow_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
