# Generated by Django 4.2.11 on 2024-04-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchwise', '0014_alter_movie_rating_alter_tvshow_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('empty', 'Empty'), ('watched', 'Watched'), ('watchlist', 'Watchlist'), ('not_interested', 'Not Interested')], default='empty', max_length=14),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='status',
            field=models.CharField(choices=[('empty', 'Empty'), ('watched', 'Watched'), ('watchlist', 'Watchlist'), ('not_interested', 'Not Interested')], default='empty', max_length=14),
        ),
    ]
