# Generated by Django 4.2.11 on 2024-04-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchwise', '0018_movie_external_id_tvshow_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('empty', 'None'), ('watched', 'Watched'), ('watchlist', 'Watchlist'), ('not_interested', 'Not Interested')], default='empty', max_length=14),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='status',
            field=models.CharField(choices=[('empty', 'None'), ('watched', 'Watched'), ('watchlist', 'Watchlist'), ('not_interested', 'Not Interested')], default='empty', max_length=14),
        ),
    ]
